# .streamlit/config.toml
[theme]
base = "dark"
primaryColor = "#00BFFF"               # bright blue accent
backgroundColor = "#0D1117"            # modern dark gray (GitHub-like)
secondaryBackgroundColor = "#161B22"   # slightly lighter card background
textColor = "#E6EDF3"
font = "sans serif"

